### ISSUE TITLE
Raising issues.

### ISSUE THREAD

**Issue by bryan11228** [dayshin/mandarinOranges#5]
We need a way to traverse through the arraylist of players after anyone but the first player raises.

ex.  Players: Eric, Bryan, Datian
If Bryan raises after Eric calls, Datian will have to call what Bryan raised, but Eric has to update his bet in compliance.  Which also raises the issue that if we traverse through the arraylist again, will Eric and Bryan call?  If so, will their balance be decremented when it should not be?

**Comment by dayshin** [comment]
Eric and Bryan calling will check instead of calling - look at the player class for details

you can test this with Woo.java...

**Comment by bryan11228** [comment]
We just need something to traverse through again then.

**Comment by dayshin** [comment]
![screenshot 2017-01-22 00 21 15](https://cloud.githubusercontent.com/assets/16548906/22180238/bb60c662-e038-11e6-9a10-ec92e7d25c2e.png)
